name: Build Windows App (Gitea)

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:  # 允许手动触发

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: 检出代码
      uses: actions/checkout@v4

    - name: 设置 Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'  # 使用最新稳定版本

    - name: 启用 Windows 桌面支持
      run: flutter config --enable-windows-desktop

    - name: 检查 Flutter 环境
      run: flutter doctor -v

    - name: 获取依赖
      run: flutter pub get

    - name: 编译 Windows Release 版本
      run: flutter build windows --release

    - name: 打包编译产物
      run: |
        cd build/windows/x64/runner/Release
        7z a -tzip ../../../../../door_designer-windows-x64.zip *

    - name: 上传编译产物
      uses: actions/upload-artifact@v4
      with:
        name: door_designer-windows-x64
        path: door_designer-windows-x64.zip
        retention-days: 30

    # 如果是 tag，创建 Release（Gitea 1.21+ 支持）
    - name: 创建 Gitea Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: https://gitea.com/gitea/release-action@main
      with:
        files: door_designer-windows-x64.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
